import type { Context } from '@deepseek-ai/cordis';
export declare const name = "community-market";
export declare const inject: string[];
export declare function apply(ctx: Context): void;
export { marketRoutes } from './host/routes.js';
export { BUILT_IN_PROVIDERS, DefaultCatalogService } from './catalog/service.js';
export { dsh1024StoreAdapter } from './adapters/dsh-1024store.js';
export { dshfindAdapter } from './adapters/dshfind.js';
export type * from './api-types.js';
export * from './contracts/index.js';
